swagger: "2.0"
info: 
  version: "0.0.1"
  title: "cpuinfo"
  description: "A simple service to get cpuinfo as an example of using swagger-2.0 specification and codegen"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Cloudmesh REST Service Example"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/engr-222"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /cpu:
    get:
      tags:
        - CPU
      operationId: os_pack.cpu.get_processor_name
      description: "Returns cpu information of the hosting server"
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "CPU info, or add more text"
          schema: 
            $ref: "#/definitions/CPU"
definitions:
  CPU:
    type: "object"
    required: 
      - "model"
    properties: 
      model:
        type: "string"
